/*! 
* DevExtreme Web
* Version: 15.2.4
* Build date: Dec 8, 2015
*
* Copyright (c) 2012 - 2015 Developer Express Inc. ALL RIGHTS RESERVED
* EULA: https://www.devexpress.com/Support/EULAs/DevExtreme.xml
*/

Globalize.addCultureInfo("cn", {messages: {
        Yes: "是",
        No: "否",
        Cancel: "取消",
        Clear: "清除",
        Done: "完成",
        Loading: "加载...",
        Select: "选择...",
        Search: "查询",
        Back: "返回",
        OK: "确认",
        "dxCollectionWidget-noDataText": "无数据",
        "validation-required": "必填",
        "validation-required-formatted": "{0}为所需格式",
        "validation-numeric": "数值",
        "validation-numeric-formatted": "{0} 数值格式",
        "validation-range": "值的范围",
        "validation-range-formatted": "{0} 数值范围格式",
        "validation-stringLength": "字符长度",
        "validation-stringLength-formatted": "{0}字符长度格式",
        "validation-custom": "定制值",
        "validation-custom-formatted": "{0} 制定值格式",
        "validation-compare": "比较",
        "validation-compare-formatted": " {0}比较格式",
        "validation-pattern": "表达式",
        "validation-pattern-formatted": "{0}表达式格式",
        "validation-email": "邮件地址",
        "validation-email-formatted": "{0} 邮件地址格式",
        "validation-mask": "屏蔽符"
}
});
Globalize.addCultureInfo("cn", "default", {
    name: "zh-CN",
    englishName: "Chinese (Simplified, PRC)",
    nativeName: "中文(中华人民共和国)",
    language: "zh-CHS",
    numberFormat: {
        "NaN": "非数字",
        negativeInfinity: "负无穷大",
        positiveInfinity: "正无穷大",
        percent: {
            pattern: ["-n%", "n%"]
        },
        currency: {
            pattern: ["$-n", "$n"],
            symbol: "¥"
        }
    },
    calendars: {
        standard: {
            days: {
                names: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
                namesAbbr: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
                namesShort: ["日", "一", "二", "三", "四", "五", "六"]
            },
            months: {
                names: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月", ""],
                namesAbbr: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月", ""]
            },
            AM: ["上午", "上午", "上午"],
            PM: ["下午", "下午", "下午"],
            eras: [{ "name": "公元", "start": null, "offset": 0 }],
            patterns: {
                d: "yyyy/M/d",
                D: "yyyy'年'M'月'd'日'",
                t: "H:mm",
                T: "H:mm:ss",
                f: "yyyy'年'M'月'd'日' H:mm",
                F: "yyyy'年'M'月'd'日' H:mm:ss",
                M: "M'月'd'日'",
                Y: "yyyy'年'M'月'"
            }
        }
    }
});
Globalize.addCultureInfo("cn", {messages: {
        "dxLookup-searchPlaceholder": "最少文字数: {0}",
        "dxList-pullingDownText": "正在下拉",
        "dxList-pulledDownText": "下拉完毕",
        "dxList-refreshingText": "正在刷新...",
        "dxList-pageLoadingText": "正在加载...",
        "dxList-nextButtonText": "下一步",
        "dxList-selectAll": "选择所有",
        "dxListEditDecorator-delete": "删除",
        "dxListEditDecorator-more": "更多",
        "dxScrollView-pullingDownText": "正在下拉",
        "dxScrollView-pulledDownText": "下拉完毕",
        "dxScrollView-refreshingText": "正在刷新...",
        "dxScrollView-reachBottomText": "达到底部",
        "dxDateBox-simulatedDataPickerTitleTime": "日期选择器",
        "dxDateBox-simulatedDataPickerTitleDate": "日期选择",
        "dxDateBox-simulatedDataPickerTitleDateTime": "日期时间选择",
        "dxDateBox-validation-datetime": "日期时间",
        "dxFileUploader-selectFile": "选择文件",
        "dxFileUploader-dropFile": "拖放文件",
        "dxFileUploader-bytes": "上传字节",
        "dxFileUploader-kb": "kb",
        "dxFileUploader-Mb": "Mb",
        "dxFileUploader-Gb": "Gb",
        "dxFileUploader-upload": "上传",
        "dxFileUploader-uploaded": "上传完毕",
        "dxFileUploader-readyToUpload": "上传就绪",
        "dxFileUploader-uploadFailedMessage": "上传文件失败",
        "dxRangeSlider-ariaFrom": "{0} 从开始",
        "dxRangeSlider-ariaTill": "{0} 到",
        "dxSwitch-onText": "开",
        "dxSwitch-offText": "关",
        "dxForm-optionalMark": "可选"
    }});
Globalize.addCultureInfo("cn", {messages: {
        "dxDataGrid-columnChooserTitle": "选择列名",
        "dxDataGrid-columnChooserEmptyText": "选择列空值",
        "dxDataGrid-groupContinuesMessage": "继续组合",
        "dxDataGrid-groupContinuedMessage": "继续组合",
        "dxDataGrid-editingEditRow": "编辑",
        "dxDataGrid-editingSaveRowChanges": "保存",
        "dxDataGrid-editingCancelRowChanges": "取消编辑",
        "dxDataGrid-editingDeleteRow": "删除",
        "dxDataGrid-editingUndeleteRow": "复原",
        "dxDataGrid-editingConfirmDeleteMessage": "您是否确定删除？",
        "dxDataGrid-validationCancelChanges": "取消修改",
        "dxDataGrid-editingConfirmDeleteTitle": "删除",
        "dxDataGrid-groupPanelEmptyText": "组合空值",
        "dxDataGrid-noDataText": "无数据",
        "dxDataGrid-searchPanelPlaceholder": "查询",
        "dxDataGrid-filterRowShowAllText": "所有",
        "dxDataGrid-filterRowResetOperationText": "重置",
        "dxDataGrid-filterRowOperationEquals": "等于",
        "dxDataGrid-filterRowOperationNotEquals": "不等于",
        "dxDataGrid-filterRowOperationLess": "小于",
        "dxDataGrid-filterRowOperationLessOrEquals": "小于等于",
        "dxDataGrid-filterRowOperationGreater": "大于",
        "dxDataGrid-filterRowOperationGreaterOrEquals": "大于等于",
        "dxDataGrid-filterRowOperationStartsWith": "起始于",
        "dxDataGrid-filterRowOperationContains": "包含",
        "dxDataGrid-filterRowOperationNotContains": "不包含",
        "dxDataGrid-filterRowOperationEndsWith": "结束于",
        "dxDataGrid-filterRowOperationBetween": "在此之间",
        "dxDataGrid-filterRowOperationBetweenStartText": "开始值",
        "dxDataGrid-filterRowOperationBetweenEndText": "结束值",
        "dxDataGrid-applyFilterText": "应用过滤条件",
        "dxDataGrid-trueText": "是",
        "dxDataGrid-falseText": "否",
        "dxDataGrid-sortingAscendingText": "升序排序",
        "dxDataGrid-sortingDescendingText": "降序排序",
        "dxDataGrid-sortingClearText": "清除排序",
        "dxDataGrid-editingSaveAllChanges": "保存修改",
        "dxDataGrid-editingCancelAllChanges": "取消修改",
        "dxDataGrid-editingAddRow": "增加行",
        "dxDataGrid-summaryMin": "最小值: {0}",
        "dxDataGrid-summaryMinOtherColumn": "{1} 列的最小值 {0}",
        "dxDataGrid-summaryMax": "最大值: {0}",
        "dxDataGrid-summaryMaxOtherColumn": "{1} 列的最大值 {0}",
        "dxDataGrid-summaryAvg": "平均值: {0}",
        "dxDataGrid-summaryAvgOtherColumn": "{1} 列的平均值 {0}",
        "dxDataGrid-summarySum": "合计: {0}",
        "dxDataGrid-summarySumOtherColumn": "{1} 列的合计 {0}",
        "dxDataGrid-summaryCount": "总数: {0}",
        "dxDataGrid-columnFixingFix": "固定",
        "dxDataGrid-columnFixingUnfix": "取消固定",
        "dxDataGrid-columnFixingLeftPosition": "向左固定",
        "dxDataGrid-columnFixingRightPosition": "向右固定",
        "dxDataGrid-exportTo": "导出",
        "dxDataGrid-exportToExcel": "导出为Excel",
        "dxDataGrid-excelFormat": "Excel格式",
        "dxDataGrid-selectedRows": "选择数据行",
        "dxDataGrid-headerFilterEmptyValue": "(空白)",
        "dxDataGrid-headerFilterOK": "确认",
        "dxDataGrid-headerFilterCancel": "清除过滤条件",
        "dxDataGrid-ariaColumn": "列",
        "dxDataGrid-ariaValue": "值",
        "dxDataGrid-ariaFilterCell": "过滤框",
        "dxDataGrid-ariaCollapse": "折叠",
        "dxDataGrid-ariaExpand": "展开",
        "dxDataGrid-ariaDataGrid": "数据表",
        "dxDataGrid-ariaSearchInGrid": "表内查询",
        "dxDataGrid-ariaSelectAll": "选择所有",
        "dxDataGrid-ariaSelectRow": "选择行",
        "dxPager-infoText": "显示{0} / {1} ({2} 的信息)",
        "dxPivotGrid-grandTotal": "合计",
        "dxPivotGrid-total": "{0} 合计",
        "dxPivotGrid-fieldChooserTitle": "选择列",
        "dxPivotGrid-showFieldChooser": "显示列选择",
        "dxPivotGrid-expandAll": "展开所有",
        "dxPivotGrid-collapseAll": "折叠所有",
        "dxPivotGrid-sortColumnBySummary": "列排序汇总",
        "dxPivotGrid-sortRowBySummary": "行排序汇总",
        "dxPivotGrid-removeAllSorting": "清除所有排序",
        "dxPivotGrid-rowFields": "行字段",
        "dxPivotGrid-columnFields": "列字段",
        "dxPivotGrid-dataFields": "数据字段",
        "dxPivotGrid-filterFields": "过滤字段",
        "dxPivotGrid-allFields": "所有字段",
        "dxScheduler-editorLabelTitle": "任务标题",
        "dxScheduler-editorLabelStartDate": "开始时间",
        "dxScheduler-editorLabelEndDate": "结束时间",
        "dxScheduler-editorLabelDescription": "任务说明",
        "dxScheduler-editorLabelRecurrence": "是否重复",
        "dxScheduler-openAppointment": "打开任务",
        "dxScheduler-recurrenceNever": "不重复",
        "dxScheduler-recurrenceDaily": "每日",
        "dxScheduler-recurrenceWeekly": "每周",
        "dxScheduler-recurrenceMonthly": "每月",
        "dxScheduler-recurrenceYearly": "每年",
        "dxScheduler-recurrenceEvery": "重复频度",
        "dxScheduler-recurrenceEnd": "结束重复",
        "dxScheduler-recurrenceAfter": "后重复",
        "dxScheduler-recurrenceOn": "开始重复",
        "dxScheduler-recurrenceRepeatDaily": "每日",
        "dxScheduler-recurrenceRepeatWeekly": "每周",
        "dxScheduler-recurrenceRepeatMonthly": "每月",
        "dxScheduler-recurrenceRepeatYearly": "每年",
        "dxScheduler-switcherDay": "日",
        "dxScheduler-switcherWeek": "周",
        "dxScheduler-switcherWorkWeek": "工作日",
        "dxScheduler-switcherMonth": "月",
        "dxScheduler-switcherTimelineDay": "时间轴（日）",
        "dxScheduler-switcherTimelineWeek": "时间轴（周）",
        "dxScheduler-switcherTimelineWorkWeek": "时间轴（周工作日）",
        "dxScheduler-switcherTimelineMonth": "时间轴（月）",
        "dxScheduler-recurrenceRepeatOnDate": "从该日开始重复",
        "dxScheduler-recurrenceRepeatCount": "重复次数",
        "dxScheduler-allDay": "全天",
        "dxScheduler-confirmRecurrenceEditMessage": "您确定重复设置的修改吗？",
        "dxScheduler-confirmRecurrenceDeleteMessage": "您确定删除重复设置的修改吗？",
        "dxScheduler-confirmRecurrenceEditSeries": "修改重复系列",
        "dxScheduler-confirmRecurrenceDeleteSeries": "删除修改重复系列",
        "dxScheduler-confirmRecurrenceEditOccurrence": "确定修改",
        "dxScheduler-confirmRecurrenceDeleteOccurrence": "确定取消",
        "dxCalendar-todayButtonText": "今日",
        "dxCalendar-ariaWidgetName": "控件名称",
        "dxColorView-ariaRed": "红",
        "dxColorView-ariaGreen": "緑",
        "dxColorView-ariaBlue": "蓝",
        "dxColorView-ariaAlpha": "透明度",
        "dxColorView-ariaHex": "色标"
}
});
